services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "1234:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-net
  spring-boot-app:
    container_name: spring-demo
    image: spring/demo
    ports:
      - "8088:8080"
    networks:
      - spring-boot-net
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  spring-boot-net:
    driver: bridge